#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http_front
    timeout client  30000
    bind *:80
    mode http
    default_backend web-servers

backend web-servers
    timeout connect  3000
    timeout server  30000
    mode http
    balance roundrobin
    server 387099-web-01 54.87.205.155:80 check
    server 387099-web-02 54.90.50.215:443 check
EOT

sudo service haproxy restart
